spring.datasource.url=jdbc:mysql://localhost:3306/cereja
spring.datasource.username=cereja
spring.datasource.password=cereja123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false